"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.submission import Submission
globals()['Submission'] = Submission
from openapi_client.model.paginated_submission_list import PaginatedSubmissionList


class TestPaginatedSubmissionList(unittest.TestCase):
    """PaginatedSubmissionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedSubmissionList(self):
        """Test PaginatedSubmissionList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedSubmissionList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
