"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.moderation import Moderation
globals()['Moderation'] = Moderation
from openapi_client.model.paginated_moderation_list import PaginatedModerationList


class TestPaginatedModerationList(unittest.TestCase):
    """PaginatedModerationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedModerationList(self):
        """Test PaginatedModerationList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedModerationList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
