"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.value_enum import ValueEnum
globals()['ValueEnum'] = ValueEnum
from openapi_client.model.vote import Vote


class TestVote(unittest.TestCase):
    """Vote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVote(self):
        """Test Vote"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Vote()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
