"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.api_api import ApiApi  # noqa: E501


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_schema_retrieve(self):
        """Test case for api_schema_retrieve

        """
        pass

    def test_api_token_create(self):
        """Test case for api_token_create

        """
        pass

    def test_api_token_refresh_create(self):
        """Test case for api_token_refresh_create

        """
        pass

    def test_api_token_verify_create(self):
        """Test case for api_token_verify_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
