"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.moderations_api import ModerationsApi  # noqa: E501


class TestModerationsApi(unittest.TestCase):
    """ModerationsApi unit test stubs"""

    def setUp(self):
        self.api = ModerationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_moderations_create(self):
        """Test case for moderations_create

        """
        pass

    def test_moderations_destroy(self):
        """Test case for moderations_destroy

        """
        pass

    def test_moderations_list(self):
        """Test case for moderations_list

        """
        pass

    def test_moderations_partial_update(self):
        """Test case for moderations_partial_update

        """
        pass

    def test_moderations_retrieve(self):
        """Test case for moderations_retrieve

        """
        pass

    def test_moderations_update(self):
        """Test case for moderations_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
