"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.user import User
globals()['User'] = User
from openapi_client.model.submission import Submission


class TestSubmission(unittest.TestCase):
    """Submission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmission(self):
        """Test Submission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Submission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
