"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.fetch_status_enum import FetchStatusEnum
globals()['FetchStatusEnum'] = FetchStatusEnum
from openapi_client.model.patched_fetch import PatchedFetch


class TestPatchedFetch(unittest.TestCase):
    """PatchedFetch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedFetch(self):
        """Test PatchedFetch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedFetch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
