"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.submissions_api import SubmissionsApi  # noqa: E501


class TestSubmissionsApi(unittest.TestCase):
    """SubmissionsApi unit test stubs"""

    def setUp(self):
        self.api = SubmissionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_submissions_create(self):
        """Test case for submissions_create

        """
        pass

    def test_submissions_destroy(self):
        """Test case for submissions_destroy

        """
        pass

    def test_submissions_fetch_destroy(self):
        """Test case for submissions_fetch_destroy

        """
        pass

    def test_submissions_fetch_retrieve(self):
        """Test case for submissions_fetch_retrieve

        """
        pass

    def test_submissions_fetch_update(self):
        """Test case for submissions_fetch_update

        """
        pass

    def test_submissions_list(self):
        """Test case for submissions_list

        """
        pass

    def test_submissions_moderation_destroy(self):
        """Test case for submissions_moderation_destroy

        """
        pass

    def test_submissions_moderation_retrieve(self):
        """Test case for submissions_moderation_retrieve

        """
        pass

    def test_submissions_moderation_update(self):
        """Test case for submissions_moderation_update

        """
        pass

    def test_submissions_partial_update(self):
        """Test case for submissions_partial_update

        """
        pass

    def test_submissions_retrieve(self):
        """Test case for submissions_retrieve

        """
        pass

    def test_submissions_update(self):
        """Test case for submissions_update

        """
        pass

    def test_submissions_votes_create(self):
        """Test case for submissions_votes_create

        """
        pass

    def test_submissions_votes_list(self):
        """Test case for submissions_votes_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
