"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.article import Article
globals()['Article'] = Article
from openapi_client.model.paginated_article_list import PaginatedArticleList


class TestPaginatedArticleList(unittest.TestCase):
    """PaginatedArticleList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedArticleList(self):
        """Test PaginatedArticleList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedArticleList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
