"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.fetch import Fetch
globals()['Fetch'] = Fetch
from openapi_client.model.paginated_fetch_list import PaginatedFetchList


class TestPaginatedFetchList(unittest.TestCase):
    """PaginatedFetchList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedFetchList(self):
        """Test PaginatedFetchList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedFetchList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
