"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.article import Article


class TestArticle(unittest.TestCase):
    """Article unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArticle(self):
        """Test Article"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Article()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
