"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.fetchs_api import FetchsApi  # noqa: E501


class TestFetchsApi(unittest.TestCase):
    """FetchsApi unit test stubs"""

    def setUp(self):
        self.api = FetchsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetchs_create(self):
        """Test case for fetchs_create

        """
        pass

    def test_fetchs_destroy(self):
        """Test case for fetchs_destroy

        """
        pass

    def test_fetchs_list(self):
        """Test case for fetchs_list

        """
        pass

    def test_fetchs_partial_update(self):
        """Test case for fetchs_partial_update

        """
        pass

    def test_fetchs_retrieve(self):
        """Test case for fetchs_retrieve

        """
        pass

    def test_fetchs_update(self):
        """Test case for fetchs_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
