"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.votes_api import VotesApi  # noqa: E501


class TestVotesApi(unittest.TestCase):
    """VotesApi unit test stubs"""

    def setUp(self):
        self.api = VotesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_votes_destroy(self):
        """Test case for votes_destroy

        """
        pass

    def test_votes_retrieve(self):
        """Test case for votes_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
