"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.moderation_status_enum import ModerationStatusEnum
globals()['ModerationStatusEnum'] = ModerationStatusEnum
from openapi_client.model.patched_moderation import PatchedModeration


class TestPatchedModeration(unittest.TestCase):
    """PatchedModeration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedModeration(self):
        """Test PatchedModeration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedModeration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
