"""
    Dognews Server API

    Dognews Server client API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.vote import Vote
globals()['Vote'] = Vote
from openapi_client.model.paginated_vote_list import PaginatedVoteList


class TestPaginatedVoteList(unittest.TestCase):
    """PaginatedVoteList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedVoteList(self):
        """Test PaginatedVoteList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedVoteList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
